name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *' # runs every day at 3 AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/dr5hn/countries-states-cities-database.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
